server:
  port: 8080

spring:
  application:
    name: dashboard-backend
  datasource:
    url: jdbc:mysql://localhost:3306/dashboard_builder?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: abcd
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql

logging:
  level:
    org.hibernate.SQL: warn
    org.hibernate.orm.jdbc.bind: warn
